version: 2.1
jobs:
  build:
    machine:
      image: python:3.7.5
    steps:
      - checkout
      - run:
          name: "Testing"
          shell: /bin/bash
          command: |
            pip install -r requirements.txt
            pip install codecov
            coverage run tests.py
      - run:
          name: get test coverage
          command: coverage
          when: always
