version: 2.1
jobs:
  build:
    docker:
      - image: python:3.7.5
    steps:
      - checkout
      - env:
          jumper_host: $jumper_host
          jumper_port: $jumper_port
          sentry_id: $sentry_id
      - run:
          name: "Testing"
          shell: /bin/bash
          command: |
            pip install coverage
            pip install -r requirements.txt
            pip install codecov
            coverage run tests.py
      - run:
          name: get test coverage
          command: coverage
          when: always
